### ISSUE TITLE
acr122_usb: touchatag 'Too small reply'

### ISSUE THREAD

**Issue by GoogleCodeExporter** [nfc-tools/libnfc#217]
```
Using nfc-list:

info    libnfc.config   Unable to open file: /etc/nfc/libnfc.conf
debug   libnfc.config   Unable to open directory: /etc/nfc/devices.d
unkown  libnfc.general  log_level is set to 3
debug   libnfc.general  allow_autoscan is set to true
debug   libnfc.general  allow_intrusive_scan is set to false
debug   libnfc.general  0 device(s) defined by user
nfc-list uses libnfc libnfc-1.6.0-rc1-184-gff3d8f7
debug   libnfc.general  0 device(s) found using pn53x_usb driver
debug   libnfc.driver.acr122_usb    device found: Bus 003 Device 002 Name ACS ACR122
debug   libnfc.general  1 device(s) found using acr122_usb driver
debug   libnfc.driver.acr122_usb    3 element(s) have been decoded from 
"acr122_usb:003:002"
debug   libnfc.driver.acr122_usb    TX: 62  00  00  00  00  00  00  01  00  00  
debug   libnfc.driver.acr122_usb    RX: 80  13  00  00  00  00  00  00  00  00  3b  
be  95  00  00  41  03  00  00  00  00  00  00  00  00  00  02  90  00  
debug   libnfc.driver.acr122_usb    ACR122 PICC Operating Parameters
debug   libnfc.driver.acr122_usb    TX: 6b  05  00  00  00  00  00  00  00  00  ff  
00  51  00  00  
debug   libnfc.driver.acr122_usb    RX: 83  00  00  00  00  00  00  40  05  00  
debug   libnfc.chip.pn53x   GetFirmwareVersion
debug   libnfc.driver.acr122_usb    TX: 6b  07  00  00  00  00  00  00  00  00  ff  
00  00  00  02  d4  02  
debug   libnfc.driver.acr122_usb    RX: 83  00  00  00  00  00  00  40  07  00  
error   libnfc.driver.acr122_usb    Too small reply
debug   libnfc.general  Unable to open "acr122_usb:003:002".
nfc-list: ERROR nfc-list.c:132
nfc-list:     Unable to open NFC device: acr122_usb:003:002

Seems like a duplicate of bug #201 but I'm using the latest from git, so it 
should be fixed. Using the acr122_pcsc driver works. 

```

Original issue reported on code.google.com by `schma...@googlemail.com` on 9 Jan 2013 at 12:31

**Comment by frustreated** [comment]
sudo LIBNFC_LOG_LEVEL=3 nfc-list
info	libnfc.config	Unable to open file: /usr/local/etc/nfc/libnfc.conf
debug	libnfc.config	Unable to open directory: /usr/local/etc/nfc/devices.d
debug	libnfc.general	log_level is set to 3
debug	libnfc.general	allow_autoscan is set to true
debug	libnfc.general	allow_intrusive_scan is set to false
debug	libnfc.general	0 device(s) defined by user
nfc-list uses libnfc libnfc-1.7.1
debug	libnfc.driver.acr122_usb	device found: Bus 002 Device 010 Name ACS ACR122
debug	libnfc.general	1 device(s) found using acr122_usb driver
debug	libnfc.driver.acr122_usb	3 element(s) have been decoded from "acr122_usb:002:010"
error	libnfc.driver.acr122_usb	Unable to claim USB interface (Device or resource busy)
debug	libnfc.general	Unable to open "acr122_usb:002:010".
nfc-list: ERROR: Unable to open NFC device: acr122_usb:002:010
----------------------------------------------------------------------------------------------------------------
**many people post problems as above ,but they are using mac system
problems as above occured in my system of ubuntu 12.06 -64
some google search said the conflict of drivers of accr122u and some chips (i don't know)
any master can give me some tips?**

**Comment by frustreated** [comment]
$ nfc-list 
nfc-list uses libnfc libnfc-1.7.1
error	libnfc.driver.acr122_usb	Unable to claim USB interface (Device or resource busy)
nfc-list: ERROR: Unable to open NFC device: acr122_usb:003:009
---------------------------------------------------------------------------------------------------------------------------------
thats the error of my nfc

**Comment by doegox** [comment]
Please open new issue and don't reuse closed bugreports on unrelated subjects (your error is not the same).
About your problem, check if you don have a conflicting kernel driver and if yes, remove it:
```
lsmod|grep pn533
modprobe -d pn533
modprobe -d pn533_usb
```
