### ISSUE TITLE
Linker gives errors with the quick_start_examples

### ISSUE THREAD

**Issue by GoogleCodeExporter** [nfc-tools/libnfc#219]
```
What steps will reproduce the problem?
1. Use the compilation  command included in the quick_start_examples files 
inside the examples/doc folder

What is the expected output? What do you see instead?
I expect a successful compilation. I instead get an error list from the linker

What version of the product are you using? On what operating system?
1.7.0 RC2 under ubuntu 12.04 and 12.10

Please provide any additional information below.
I solved as follows:
instead of compiling with the suggested command which is:
gcc -o quick_start_example1 -lnfc  quick_start_example1.c

I compiled with the following command:
gcc -o quick_start_example1  quick_start_example1.c -lnfc 

I would suggest to insert this new command into the quick_start_examples files



```

Original issue reported on code.google.com by `lark...@gmail.com` on 23 Jan 2013 at 2:17

**Comment by tenznhok** [comment]
I got the same problem. What did you do to fix it?

**Comment by fishbone1** [comment]
Simply put `-lnfc` after your source file. The order matters for the linker! If you put the lib first, the linker has no use for it and could ignore it...

And yes, I think there are differences regarding the gcc version. I get this error with the arm cross compiler (running on linux), but not with same version of gcc on the target arm device.

This should work:

`gcc quick_start_example1.c  -lnfc -o quick_start_example1`
