### ISSUE TITLE
nfc-list fails with PN533 usb device

### ISSUE THREAD

**Issue by GoogleCodeExporter** [nfc-tools/libnfc#221]
```
What steps will reproduce the problem?
1. Build and install libnfc-1.7.0-rc2 from source
2. Insert NXP PN533 usb NFC reader
3. run sudo nfc-list


What is the expected output? What do you see instead?

I expect a list of nearby nfc tags. Instead I get:

nfc-list uses libnfc libnfc-1.7.0-rc2
error   libnfc.driver.pn53x_usb Unable to set USB configuration (Device or 
resource busy)
No NFC device found.



What version of the product are you using? On what operating system?

libnfc-1.7.0-rc2 on Arch Linux x86_64 with kernel 3.6.11



Please provide any additional information below.

dmesg:

[ 3029.399082] pn533 4-2:1.0: NFC: NXP PN533 firmware ver 2.7 now attached
[ 3034.547509] usb 4-2: usbfs: interface 0 claimed by pn533 while 'nfc-list' 
sets config #1
```

Original issue reported on code.google.com by `la...@lrvick.net` on 25 Jan 2013 at 6:16

**Comment by Baternest** [comment]
It's work for me too!

**Comment by Kodmit** [comment]
modprobe -r pn533 work for me, don't forget to unplug and replug the NFC reader

**Comment by lunaxynovev** [comment]
Hello everyone,
although this thread has been inactive for a long time, i would like to know if anyone has found another solution 

I'm trying to read MIFARE card data

I have tried all the proposed solutions I could find on github and other websites but nothing works

I have reinstalled libnfc and Ubuntu several times and I could conclude that : 
when I use the command "sudo nfc-list" without placing the card on the reader and just after a reinstallation it works and the device is detected, I get
`user@ubuntu:~/Desktop$ sudo nfc-list 
nfc-list uses libnfc 1.7.1
NFC device: NXP / PN533 opened`


then I do the command "sudo nfc-list" with the MIFARE card and I get 
`user@ubuntu:~/Desktop$ sudo nfc-list
nfc-list uses libnfc 1.7.1
NFC device: NXP / PN533 opened
1 ISO14443A passive target(s) found:
ISO/IEC 14443A (106 kbps) target:
    ATQA (SENS_RES): 00  04  
       UID (NFCID1): 74  b7  cf  bd  
      SAK (SEL_RES): 18  `


but right after the "sudo nfc-list" command works, if I use the "sudo nfc-list" command I get 
`user@ubuntu:~/Desktop$ sudo nfc-list
nfc-list uses libnfc 1.7.1
error	libnfc.driver.pn53x_usb	Unable to set USB configuration (Broken pipe)
No NFC device found.
`


every time I want to use the "sudo nfc-list" command , I have to completely reinstall Ubuntu and libnfc
