### ISSUE TITLE
nfc-list.exe fails to claim USB interface

### ISSUE THREAD

**Issue by GoogleCodeExporter** [nfc-tools/libnfc#253]
```
What steps will reproduce the problem?
1. compile libnfc 1.7.0 RC7
2. plug in ACR122U reader
3. start nfc-list.exe

What is the expected output? What do you see instead?
nfc-list.exe uses libnfc 1.7.0
error   libnfc.driver.acr122_usb        Unable to claim USB interface 
(libusb0-dll:err [claim_interface] could not claim interface 0, win error: 
Command not recognized
)
ERROR: Unable to open NFC device: acr122_usb:bus-0:\\.\libusb0-0001-x072f-0x90cc


What version of the product are you using? On what operating system?
libnfc 1.7.0 RC7, Windows 7 64-bit

Please provide any additional information below.
Compiled with CMake-gui, mingw64
```

Original issue reported on code.google.com by `boska.mi...@gmail.com` on 29 Jun 2013 at 10:44

**Comment by SebaZ** [comment]
Problem is with driver on Windows. If you used instructions from http://www.mobilefish.com/developer/libnfc/libnfc.html and it's modyfication on WIndows 8, WIndows 10 http://dld.is.d-logic.net/dld/LibNFC/Installing%20PN533%20and%20libNFC%20onto%20Windows%208-1.pdf just use libusbK as a driver with Zadig software to change driver to libusb which works.

**Comment by neomilium** [comment]
Reported to work correctly with a correct setup.
