### ISSUE TITLE
nfc-mfclassic fail at writting tag

### ISSUE THREAD

**Issue by GoogleCodeExporter** [nfc-tools/libnfc#269]
```
Hi everybody, i'm trying to write my card but i can't i have the same error.
This fail only occur with an specific tag with some other tags had been wrote 
succesfully .
Im'm using libnfc 1.7 in debian 7 with  a linux kernel version 3.2.0-4.
root@debian-vm:/home/berni/rfid/# nfc-mfclassic w b "berni_no.mdf" 
"berni.15-8.mfd" 
NFC reader: SCM Micro / SCL3711-NFC&RW opened
Found MIFARE Classic card:
ISO/IEC 14443A (106 kbps) target:
    ATQA (SENS_RES): 00  04  
       UID (NFCID1): 0d  de  59  a1  
      SAK (SEL_RES): 08  
Guessing size: seems to be a 1024-byte card
Writing 64 blocks |.xroot@debian-vm:/home/berni/rfid/#


I expected something like this at the output:

Writing 64 blocks 
|................................................................|


I've been wrote this card with older versions of libnfc but with the lastest i 
can not write in the tag.
Have you any idea about what's happening?


```

Original issue reported on code.google.com by `berni.emerald@gmail.com` on 25 Feb 2014 at 11:21

**Comment by neomilium** [comment]
Not enough information to process it.
Please reopen with useful files : debug trace, current card dump and injected dump.

**Comment by anthonyraymond** [comment]
Hi,

I was also encourteing this issue.
Thanks to this guy: https://github.com/nfc-tools/libnfc/issues/410#issuecomment-299206996 i managed to get it solved. (for every other people that would come by this issue i'll post a link to the solution)

As silly as it sounds you should try to lift the tag from the reader by putting some sheets of paper between the reader and the tag. I worked for me, and i had the exact same issue.

I definely known that this sounds like bulls**t, and i can't undertand why it works but...

**Comment by s1shed** [comment]
> I definely known that this sounds like bulls**t, and i can't undertand why it works but...

It sounds like BS, but it worked for me too...
