### ISSUE TITLE
Add cmake config files

### ISSUE THREAD

**Issue by GoogleCodeExporter** [nfc-tools/libnfc#275]
```
Hi,

Here's a patch to add cmake config files, this way you can detect libnfc from 
another cmake project by just writing:

find_package(LibNFC NO_MODULE REQUIRED)
include(${LIBNFC_USE_FILE})
add_executable(ex1 nfc-anticol.c)
target_link_libraries(ex1 ${LIBNFC_LIBRARIES})

and by passing -DLibNFC_DIR=<prefix>/lib/cmake/libnfc to cmake if not in a 
system dir.

just add the .cmake and .cmake.in in the cmake folder.

Regards,
J.
```

Original issue reported on code.google.com by `julien.s...@gmail.com` on 21 Mar 2014 at 1:30

Attachments:
* [libnfc-cmake_config.patch](https://storage.googleapis.com/google-code-attachments/libnfc/issue-275/comment-0/libnfc-cmake_config.patch)
* [LibNFCConfig.cmake.in](https://storage.googleapis.com/google-code-attachments/libnfc/issue-275/comment-0/LibNFCConfig.cmake.in)
* [UseLibNFC.cmake](https://storage.googleapis.com/google-code-attachments/libnfc/issue-275/comment-0/UseLibNFC.cmake)

**Comment by neomilium** [comment]
Fixed in ef74d81a8b24898cb686510b6fec76dcfdc149d2
