### ISSUE TITLE
Wrong open mode for file descriptor 4 in utils/nfc-relay-picc.c

### ISSUE THREAD

**Issue by GoogleCodeExporter** [nfc-tools/libnfc#280]
```
The open mode for fdopen of file descriptor 4 in nfc-relay-picc utility should 
be "w", not "r". Otherwise the utility fails when it tries to write into this 
descriptor.

Note: this affects when the utility is run in initiator mode only.

See attached patch.
```

Original issue reported on code.google.com by `ondrej.m...@gmail.com` on 29 Jun 2014 at 12:40

Attachments:
* [libnfc-relay-picc.patch](https://storage.googleapis.com/google-code-attachments/libnfc/issue-280/comment-0/libnfc-relay-picc.patch)

**Comment by neomilium** [comment]
Thanks
