### ISSUE TITLE
Invalid RDR_to_PC_DataBlock frame with ACR122U

### ISSUE THREAD

**Issue by GoogleCodeExporter** [nfc-tools/libnfc#284]
```
Context: when using nfc-poll with an ACR122U chipset ( 
http://nfc-tools.org/index.php?title=ACR122 ), I get those errors: 

nfc-poll uses libnfc libnfc-1.7.1-12-gb978c45
NFC reader: ACS / ACR122U PICC Interface opened
NFC device will poll during 30000 ms (20 pollings of 300 ms for 5 modulations)
error   libnfc.driver.acr122_usb        Invalid RDR_to_PC_DataBlock frame
nfc_initiator_poll_target: Input / Output Error

What steps will reproduce the problem?
1. launch nfc-poll
2. wait

What version of the product are you using? On what operating system?
Archlinux, libnfc-git version compiled today.


Please provide any additional information below:
Everything works fine beside that: mfoc, nfc-mfclassic…

```

Original issue reported on code.google.com by `grunbla...@gmail.com` on 19 Oct 2014 at 8:37

**Comment by exander77** [comment]
I am getting this bug too, it is rather serious, because after a while polling start to fail, I have to disconnect the device to make it work again.

Did a little investigation: acr122_usb_bulk_read is returning 10

**Comment by exander77** [comment]
What is the status? The ACR122U is unusable with this bug.

Can I do something to speed up the fix?

**Comment by wildattire** [comment]
I can confirm this, but in a different setting. Any attempt to call nfc_initiator_select_passive_target(), regardless of parameters, results in the following:

debug	libnfc.chip.pn53x	InListPassiveTarget
debug	libnfc.chip.pn53x	No timeout
debug	libnfc.driver.acr122_usb	TX: 6f 09 00 00 00 00 00 00 00 00 ff 00 00 00 04 d4 4a 01 00 
debug	libnfc.driver.acr122_usb	RX: 80 00 00 00 00 00 00 00 fe 00 
error	libnfc.driver.acr122_usb	Invalid RDR_to_PC_DataBlock frame
debug	libnfc.driver.acr122_usb	ACR122 Abort

This is a total showstopper for us.

**Comment by exander77** [comment]
Yes, this:
```
debug libnfc.driver.acr122_usb RX: 80 00 00 00 00 00 00 00 fe 00
```
is exactly what I am getting, this ten byte response.

**Comment by exander77** [comment]
Can I do something to speed up this bugfix?

**Comment by neomilium** [comment]
@exander77 We (core team) do the support on our spare time but do not have so much this period. If you would like to have a professional support, we can offer one. If you would like to see the bug fixed out side of professional scope, feel free to submit a PR and we will have a look to it, ASAP.
Thanks for your understanding

**Comment by andrea-spotsoftware** [comment]
Any news about it?

**Comment by lcrocker** [comment]
Is this perhaps related to #472, for which there is a patch?

**Comment by triple2digital** [comment]
Does anyone have a solution to this yet? Here is my output

i@raspberrypi:~ $ sudo nfc-poll 
nfc-poll uses libnfc 1.7.1
NFC reader: ACS / ACR122U PICC Interface opened
NFC device will poll during 30000 ms (20 pollings of 300 ms for 5 modulations)
error	libnfc.driver.acr122_usb	Invalid RDR_to_PC_DataBlock frame
nfc_initiator_poll_target: Input / Output Error

**Comment by ArcadeHustle** [comment]
I believe I am running into this with nfs-relay-picc 
...
error	libnfc.driver.acr122_usb	Invalid RDR_to_PC_DataBlock frame
nfc-relay-picc: ERROR: Initialization of NFC emulator failed

**Comment by neomilium** [comment]
ACR122U is bogus, at least some of them (depending on firmware).
Feel free to open a new issue with details, run libnfc in debug mode and dig what is going one.
Try with 1.8.0.
PR is welcome.
