### ISSUE TITLE
Support for ACS ACR1251U Reader

### ISSUE THREAD

**Issue by GoogleCodeExporter** [nfc-tools/libnfc#285]
```
At the moment the ACS ACR1251U is not supported by LibNFC (only it's 
predecessor the ACS ACR122U is).

Is it possible add support for the ACS ACR1251U, and what information do i need 
to provide?


http://www.acs.com.hk/en/products/218/acr1251-usb-nfc-reader-ii/#tab_techspecs
```

Original issue reported on code.google.com by `collin.b...@gmail.com` on 13 Nov 2014 at 12:39

**Comment by mateuscb** [comment]
Just came across the same problem, any updates on possible support?

**Comment by neomilium** [comment]
Nobody in the core team is working on it, but : 
1) IMHO, its possible to support this device.
2) Anyone (including you :) ) can fork libnfc and try to support it
3) If you dont want to do it yourself, you hire our skills

**Comment by kingofnerds** [comment]
I have forked libnfc and am trying to make it work, but without much success.

**Comment by neomilium** [comment]
Is this device really different from ACS ACR122 (technically) ?

**Comment by kingofnerds** [comment]
I have never used an ACR122, and I actually have the ACR1252U not the ACR1251, so I don't know the differences.

**Comment by mateuscb** [comment]
@neomilium cool, thanks for the info. For now, i was able to acquire a ACR122 device.

**Comment by neomilium** [comment]
This issue is old and and have no recent comment. The code may have been fixed upstream.
Please reopen if relevant.

**Comment by itsnuwan** [comment]
Still no Support for ACS ACR1251U Reader. Please advice if otherwise. It it is then please reopen this issue

**Comment by doegox** [comment]
See issue #409 for technical details

**Comment by djwel** [comment]
Hi, 
I no this post is old but, I can ask if someone have any news on this ? 
I’ve a ACR1251u reader and I will work with libnfc 
Thank you
