### ISSUE TITLE
PN532 frame preamble parsing shortcoming

### ISSUE THREAD

**Issue by GoogleCodeExporter** [nfc-tools/libnfc#289]
```
What steps will reproduce the problem?

1. PICC emulation using pn532_uart driver and Adafruit PN532 board.
2. Communication interrupts with "Frame preamble+start code mismatch"

What is the expected output? What do you see instead?

According to NXP PN532 user manual rev 0.2, frame preamble can be longer than 
one zero byte - see chapter 6.2.1.6. Currently, libnfc hardcodes 0x00, 0x00, 
0xFF as preamble, failing on 0x00, 0x00, 0x00, 0xFF (for example).
Instead, you should skip leading zeroes up to first 0xFF byte.

What version of the product are you using? On what operating system?

libncf-1.7.1, the same issue is in git master branch, commit 108de27c1b45.

```

Original issue reported on code.google.com by `ro...@jikos.cz` on 24 Feb 2015 at 5:10

**Comment by neomilium** [comment]
This issue is old and and have no recent comment. The code may have been fixed upstream.
Please reopen if relevant.

**Comment by ilario** [comment]
Just observed this error today.

Setup:
Arch Linux (libnfc 1.8.0)
USB-to-Serial FT232RL
PN532
Mifare Classic 4k card

Error:
```
error	libnfc.driver.pn532_uart	Frame preamble+start code mismatch
nfc_initiator_init: Input / Output Error
error	libnfc.chip.pn53x	Unexpected PN53x reply!
```

I never tried to read a 4k card before, but from what I understood my PN532 should be able to do that, right? (and is working well with the 1k cards I have)
The content of the `abtRxBuf` array changes every time I try to read the card (I managed to simply access it adding the values to the error message as you can see here: https://github.com/ilario/libnfc/blob/2d821a623d08bb224ed7f07687f5a4de5374fbfb/libnfc/drivers/pn532_uart.c#L400 ), for example, reading the card a few times, the content of the array is like these lines (one line per read):
```
E140EC37F900
80848A377E00
204020DFE100
24FA92D5F300
C2A0FF37FF00
88F8FDFEC800
```

According to Mifare Classic Tool app I have on the phone, the card is a:
Type: MIFARE Classic 4k, NXP
ATQA: 0042
SAK: 18
ATS: -
Memory size: 4096 byte
Block size: 16 byte
Number of sectors: 40
Number of blocks: 256

and the app can read well the card (from sector 0 to 34 there's no data, from sector 35 to 39 it is locked with key).
Thanks for your work! Please let me know if I can help further.
