### ISSUE TITLE
Improving versioning

### ISSUE THREAD

**Issue by smortex** [nfc-tools/libnfc#299]
#298 makes me realize that the `NEWS` file reference lots of random API breakages.  I think we can do better ;-)

Common schemes:
1. [semantic versionning](http://semver.org/) would allow a match between the project version and the `.so.X` file on disk (at least, I think it should).  This means jumping to version 5 or 6;
2. [odd unstable even stable](http://stackoverflow.com/questions/1266411/which-open-source-projects-use-odd-unstable-even-stable-style-of-versioning) makes it super-easy to determine if a given version is stable or not.

This practice could be enlarged to match all nfc-tools projects.

Any though?

**Comment by fuzxxl** [comment]
Maybe you could just try harder not to break the API every other version? It's not that difficult.

**Comment by neomilium** [comment]
@fuzxxl we are trying to not break API but sometimes its needed... How your comment could be useful?

**Comment by fuzxxl** [comment]
@neomilium  Well, in the last case (cf. issue #298) it wasn't actually needed to break the API but you still did. Breaking the API is required much less often then it seems on first glance. You could do a great service to your users by trying harder not to break the API, even when the result might be slightly less beautiful than a broken API; that's what I tried to say with my comment.

**Comment by smortex** [comment]
Hello, it's 2017! [SemVer](http://semver.org/) FTW!
