### ISSUE TITLE
nfc-emulate-forum4

### ISSUE THREAD

**Issue by davidferreira90** [nfc-tools/libnfc#307]
Hi everyone,

Just one question. I'm using pn532 on raspberry pi.
My problem is: if i make "sudo nfc-emulate-forum-tag4" and touch the transceiver(pn532) with myphone(samsung galaxy coreprime), most of time nothing happens , and touch again, and again, and again.... and finally my phone open the browser and the communication it's done.
then i try again( sudo nfc-emulate-forum-tag4) and it's all over again.

Someone can help me?

Thanks (sorry my english)

**Comment by neomilium** [comment]
Please use the mailing list or StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only.
