### ISSUE TITLE
Question on Mifare data in sectors and block

### ISSUE THREAD

**Issue by Monochrome4** [nfc-tools/libnfc#318]
Hi, i have a question regarding mifare cards containing credits to be used. Usually there would be a sector, say sector 2. Block 1 and Block 2 will contain 32 bytes of hex values each. By editing block 1, i am able to set the values to the amount of credit i want. Theres no need to edit the value of block 2. 

So what is the purpose of block 2?

**Comment by smortex** [comment]
Please use the mailing list or StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only.
