### ISSUE TITLE
tag right version

### ISSUE THREAD

**Issue by n0way0ut** [nfc-tools/libnfc#320]
hello,

is there a method to know the exact version of a tag? i.e. not only "mifare ultralight" but also if it is ev1 or not.

Thanks,
-nw

**Comment by neomilium** [comment]
https://github.com/nfc-tools/nfcutils

**Comment by neomilium** [comment]
Please use the mailing list or StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only.
