### ISSUE TITLE
Can Not Compile Win64 Binary

### ISSUE THREAD

**Issue by gudenau** [nfc-tools/libnfc#332]
I have managed to get a build working on Windows, but I can not get it to build a 64 bit version of libnfc. Whenever I add -m64 to the CFLAGS the build breaks and it complains about redefining macros, missing symbols and 64 bit reallocations.

**Comment by doegox** [comment]
Can you check against the current HEAD?
11a2da28 may have fixed your problem

**Comment by smortex** [comment]
Closing as @doegox gave a solution.  Please reopen if it does not fix your issue.
