### ISSUE TITLE
README incorrect: INSTALL file does not exist

### ISSUE THREAD

**Issue by kmoe** [nfc-tools/libnfc#333]
This line of the README directs the reader to an INSTALL file: https://github.com/nfc-tools/libnfc/blob/master/README#L49

Unfortunately, there is no INSTALL file in the repo!

**Comment by neomilium** [comment]
INSTALL file is generated using "autoreconf -is" and is available in archive but not in development version.
http://nfc-tools.org/index.php?title=Libnfc#Development_version

**Comment by kmoe** [comment]
Thanks!
