### ISSUE TITLE
Request to add Omnikey Cardman 5121

### ISSUE THREAD

**Issue by rhyaam** [nfc-tools/libnfc#334]
Omnikey Cardman 5121

lsusb

Bus 007 Device 004: ID 076b:5121 OmniKey AG CardMan 5121

**Comment by Maxhy** [comment]
This reader is not a PNxxx based chip, pingback to http://forums.nfc-tools.org/topic/117/compatibility-with-omnikey-5321-devices/
I would recommend to use a PC/SC library instead for now.
