### ISSUE TITLE
Change SAK on UID changeable Mifare Classic 1k?

### ISSUE THREAD

**Issue by 0ut0fb0unds** [nfc-tools/libnfc#336]
Is it possible to change the SAK on a UID changeable Mifiare Classic 1k card with nfc-tools?

It looks like this is possible with a proxmark3. I see nfc-tools has nfc-mfsetuid, but according to the man page only 4  Byte  UID  is  supported.

When I clone a card with nfc-mfclassic the UID is written properly, but the SAK is not changed.

Just wondering if there is something I am missing, or if this is currently not possible with nfc-tools.

**Comment by quantum-x** [comment]
This is more a question of chipset.
Some badges will allow for the changing of SAK, some won't.
The easiest way to modify the SAK is the change the value in your hex dump directly, and then write that to the badge.

There are many variations of badges floating around - roughly speaking, 3 generations, with multiple variations. Some accept SAK variations, some don't.
