### ISSUE TITLE
Since I disabled the pn533, the LED and Buzzer on the ACR122U doesn't work. 

### ISSUE THREAD

**Issue by comseong** [nfc-tools/libnfc#338]
I am using acr122u-a9 at Raspberry-pi 2 with Raspbian. 
When the ACR122U is plugged in, kernel(>3.5) will automatically load the pn533 driver. With the pn533 driver, pcscd will report "Can't claim interface" error. When I disabled pn533 in kernel with blacklist.conf, the error will be disappeared.
But since I disabled the pn533, the LED and Buzzer on the ACR122U doesn't work. 
How can I solve this problem?
Thanks.

**Comment by neomilium** [comment]
ACR122U do not use PN533 but PN532.
PCSC is not related to libnfc (acr122-pcsc driver in libnfc is deprecated).
