### ISSUE TITLE
pn53x_usb: nfc_list_devices() fails to list already opened devices

### ISSUE THREAD

**Issue by philenotfound** [nfc-tools/libnfc#339]
Device was openend with nfc_open(), then I tried to list available devices and the before opened device is missing in the returned list.

libnfc throws this error:
"error   libnfc.driver.pn53x_usb Unable to set USB configuration (Device or resource busy)"

The culprit seems to be in [pn53x_usb.c line 216](https://github.com/nfc-tools/libnfc/blob/master/libnfc/drivers/pn53x_usb.c#L216).

Is that usb_set_configuration() doing anything? Seems very intrusive for just listing available devices.
I removed it for testing purposes and it fixes my problem.

acr122_usb had that same usb_set_configuration removed with 70484509afe1475570fc9c7682a701928dd93a89

If you agree I'll open a PR for the fix.

Thanks!

**Comment by smortex** [comment]
Feel free to submit PR directly : the nfc-tools contributors work on the project on a best effort basis.  I have no idea whether the change you are proposing would be OK or not, but if you provided a PR, I could test it and provide feedback.  Thanks!
