### ISSUE TITLE
I write wrong BCC byte

### ISSUE THREAD

**Issue by aleks921** [nfc-tools/libnfc#351]
I buy magic card with direct comand change uid. I write in this card uid with wrong BCC byte and acr122 don't see now this card. How restore this card ? Help me, please.

**Comment by smortex** [comment]
Please use the mailing list or StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only.

**Comment by aleks921** [comment]
What about forums and milliing list ? why you can not help with this problem ?
