### ISSUE TITLE
RF Transmission Error on nfc-relay

### ISSUE THREAD

**Issue by Galile0** [nfc-tools/libnfc#358]
Hey, I have been trying to get a very simple setup of 
[genuine reader->Reader 1(target)->Laptop->Reader 2(initiator)->genuine Tag] going. For the relay I use two reader with an Pn533 Chip I had lying around, and an Android Phone as my genuine reader. The script I use is the nfc-relay script from the examples.
But the only transmission I get is an WakeUp request (0x52), and the ATQA (0x0400). After that libnfc spams me with -20 Rf Transmission Error.
I Know that relay attacks are prone to timing issues, but the error seems a bit unspecific for that (I noticed there would be a potential timeout error too)
Any ideas why this is happening/How to fix it?

Here is a debug log of the whole procedure:
http://pastebin.com/wv8Kb4Zk

**Comment by neomilium** [comment]
Its definitively a timing issue due to hardware and short timing requirements.

The only way to replay/sniff transmission using PC is with dedicated hardware (e.g. proxmark).
