### ISSUE TITLE
Error while compiling example - nfc emulate (undefined reference to `print_hex')

### ISSUE THREAD

**Issue by crockkaw** [nfc-tools/libnfc#371]
I'm trying to compile one of examples nfc-emulate-forum-tag2.c and i am getting something like that: 

> root@.............../libnfc# gcc -o emulate nfc-emulate-forum-tag2.c -lnfc
> /tmp/ccIBZkem.o: In function `nfcforum_tag2_io':
> nfc-emulate-forum-tag2.c:(.text+0x91): undefined reference to `print_hex'
> nfc-emulate-forum-tag2.c:(.text+0x178): undefined reference to `print_hex'
> collect2: error: ld returned 1 exit status

Any idea why i got this error ? 
How to make it worked ?

**Comment by doegox** [comment]
Just use cmake, it'll compile examples too:
```
mkdir build && cd build && cmake .. && make && ls -l examples
```

Or fix your command line with
```
gcc -I .. -o emulate nfc-emulate-forum-tag2.c ../utils/nfc-utils.c -lnfc
```
