### ISSUE TITLE
LibUSB ./configure error

### ISSUE THREAD

**Issue by Azef1** [nfc-tools/libnfc#373]
Hi, 

When i do `./configure` to install lib-nfc 1.7.1 i have this error:
```
checking which drivers to build... acr122_usb
checking for documentation request... no
./configure: line 14026: syntax error near unexpected token `libusb,'
./configure: line 14026: `        PKG_CHECK_MODULES(libusb, libusb, HAVE_LIBUSB=1, HAVE_LIBUSB=0)'

```
So, i did `apt-get install libusb-dev` 
```
Reading package lists... Done
Building dependency tree       
Reading state information... Done
libusb-dev is already the newest version (2:0.1.12-30).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
```
But i always have the same error when i do ./configure

Could-you help me ?

 My NFC reader is ACR122U and i work on kali linux

**Comment by BuptPeter** [comment]
mayby you can try use:
autoconfig -vis
(you have to install autoconf at first.)

**Comment by doegox** [comment]
You got the error
```
./configure: line 14026: syntax error near unexpected token `libusb,'
./configure: line 14026: `        PKG_CHECK_MODULES(libusb, libusb, HAVE_LIBUSB=1, HAVE_LIBUSB=0)'
```
because you're missing `libglib2.0-dev`. Install it and try again:
```
apt-get install libglib2.0-dev
autoreconf -vis
./configure
make
```

**Comment by smortex** [comment]
Closing as @doegox gave a solution.  Please reopen if this does not fix your problem.

**Comment by Krazubu** [comment]
I'm getting the same error with 1.5.1, however doing
```
apt-get install libglib2.0-dev
autoreconf -vis 
```
does not help

**Comment by symdeb** [comment]
From clean Ubuntu I had to install
build-essentials
autoconf
libusb-1.0
libudev-dev
libglib2.0-dev

**Comment by bosgnoom** [comment]
> libusb-compat.

Installing libusb-compat and libusb-compat-devel did it for me on fedora 41
