### ISSUE TITLE
Connect to PN65 (PN544) NFC reader

### ISSUE THREAD

**Issue by pruwait** [nfc-tools/libnfc#374]
I can't connect to internal NXP PN65 (PN544) NFC reader on Asus Nexus 7 2012.
`nfc-list
No NFC devices found`  

Need support device /dev/pn544

**Comment by doegox** [comment]
PN544 is entirely different chip and is not supported by libnfc.
Adding support would be a major work.
Sorry.

**Comment by mirh** [comment]
PN65 is basically PN544 plus smartmx
https://books.google.it/books?id=_Ta3BAAAQBAJ&pg=PA360

**Comment by okias** [comment]
oh, that's bad :(
