### ISSUE TITLE
NFC-Tools website disappeared

### ISSUE THREAD

**Issue by Davideddu** [nfc-tools/libnfc#390]
Your website is not working, I don't know any other way to contact you other than opening an issue.
The website disappeared today, it's been replaced with this weird aviation megastore thing: https://postimg.org/image/b3vf0yqpl/
Just in case you weren't aware.
Have a nice day

**Comment by 12458** [comment]
I am also experiencing the same problem. Maybe the domains got mixed up?

**Comment by doegox** [comment]
Thanks for the notification, I'm trying to reach the owner. DNS seems ok, looks more like defacing via redirection (err 301).

**Comment by Xoib** [comment]
If the administrator needs help, I can offer some sysadmin skills.

**Comment by smortex** [comment]
@doegox, it seems to be fixed, as far as I can see.

**Comment by Davideddu** [comment]
@smortex I can confirm that.

**Comment by smortex** [comment]
Excellent, thank you for your quick report ;-)
