### ISSUE TITLE
Update contrib/linux/blacklist-libnfc.conf to blacklist pn533_usb

### ISSUE THREAD

**Issue by rhertzog** [nfc-tools/libnfc#391]
contrib/linux/blacklist-libnfc.conf needs to be updated to also blacklist pn533_usb. This has been reported to Kali with this bug:
https://bugs.kali.org/view.php?id=3645

Thank you in advance.

**Comment by doegox** [comment]
Hi Raphaël
Thanks, this is fixed.
Note that on your side debian/README.Debian text should be adapted to add pn533_usb too.
