### ISSUE TITLE
Unable to use mfsetuid

### ISSUE THREAD

**Issue by Kinny092** [nfc-tools/libnfc#395]
I had found out that mfsetuid will solve many of my problems, as to cloning cards by backdoor it and to repair corrupted cards. 

I have Libnfc 1.7.1-4 installed, i can use:
nfc-emulate-forum-tag4, nfc-list, nfc-mfclassic, nfc-mfultralight, nfc-read-forum-tag3, nfc-relay-picc, nfc-scan-device

but i can not use mfsetuid at all. I had tried to reconfigure it, remake it but it is still not working. 
The card reader i am using is acr122u. 

Thanks

**Comment by Georges760** [comment]
You need special Chinese Mifare 1K card for this command. Normal card does
not allow to change UID...

**Comment by Kinny092** [comment]
the ones i bought are the special ones which allows uid to be changed. however, i believe my problem lies on the software side.

**Comment by doegox** [comment]
6c44c20ffce6b4f2e725f13fbb3fc49f6ae6d1bf has been integrated today with support for yet another type of magic cards, you may try compiling the latest sources.

**Comment by Kinny092** [comment]
i have checked my source and it does have those lines of codes installed.

**Comment by doegox** [comment]
Maybe you've yet another type of card.
Can you give details ? Can you use other software to set the UID ?

**Comment by Kinny092** [comment]
hmm, the details.. do you mean the sector 0 of the dummy card? i do have ACS software but it dosent seem to work. besides, i would prefer mfsetuid as i want to use linux instead of switching system

**Comment by doegox** [comment]
No I mean details about your magic card as it seems not recognized by mfsetuid, but now you're telling me that it doesn't work with the original software neither so maybe your card is just not functioning properly.

**Comment by Kinny092** [comment]
The thing is, the libnfc does work but does not change sector 0, it only copies the contents of other sectors. 
The ACS software i got from the vendor dosent seem to copy sector 0 either. Im guessing i do not know how to use the ACS software and mfsetuid just dosent work on my box for some reason. 

https://www.aliexpress.com/item/Free-Shipping-5pcs-lot-UID-Changeable-MF-1K-NFC-Keyfobs-13-56MHz-Block-0-sector-zero/32682486174.html

**Comment by neomilium** [comment]
Agreed with @doegox , it appears to come for your card.

**Comment by Kinny092** [comment]
I know why, i fixed it. It is working now. BUT its NOT because of my card :)

**Comment by doegox** [comment]
The mystery remains...

**Comment by wpc009** [comment]
> I know why, i fixed it. It is working now. BUT its NOT because of my card :)

How do you fixed it? I have the same issue with you. Can you share your solution to this?

**Comment by Kinny092** [comment]
Sorry its been some time since i touched alot on nfc. To my best memory there is a parameter i had to enter with the uid but if that doesn't work, i don't think its possible with linux yet. My latest way of cloning the card is to use a windows acs software which is very much hassle free.

**Comment by wpc009** [comment]
> Sorry its been some time since i touched alot on nfc. To my best memory there is a parameter i had to enter with the uid but if that doesn't work, i don't think its possible with linux yet. My latest way of cloning the card is to use a windows acs software which is very much hassle free.

Thanks anyway.
