### ISSUE TITLE
Publishing API

### ISSUE THREAD

**Issue by neomilium** [nfc-tools/libnfc#403]
While updating [releasing process page](https://github.com/nfc-tools/libnfc/wiki/ReleasingProcess), I realized we do not have API hosting place anymore.

Do you know where can we put this information ?

**Comment by smortex** [comment]
Found this:
http://stackoverflow.com/a/37243445

**Comment by doegox** [comment]
ReadTheDocs is only for Python AFAIK.
Moreover it's not easy to tune.

**Comment by doegox** [comment]
Maybe sth like this? https://gist.github.com/vidavidorra/548ffbcdae99d752da02
Travis -> GH-pages

**Comment by smortex** [comment]
We might reconsider this in the future
