### ISSUE TITLE
Forum is not reachable anymore

### ISSUE THREAD

**Issue by neomilium** [nfc-tools/libnfc#404]
I updated wiki page, we need to update README.md too.

**Comment by neomilium** [comment]
For users questions, do we accept them on GitHub issues or should we send users somewhere else ? (e.g. StackOverFlow, GoogleGroups)

**Comment by neomilium** [comment]
IMHO, developers could go in GH issue tracker. Are you agree ?

**Comment by doegox** [comment]
The forum was a good place.
The issue with the forum being broken has been reported to Roel on 27/03, no reaction so far.

**Comment by doegox** [comment]
Developer questions in GH, yes no prob.

**Comment by anik786** [comment]
Why is the forum not reachable anymore: http://forums.nfc-tools.org/

It just says:

> This PHP environment doesn't have SQLite support built in. SQLite support is required if you want to use a SQLite database to run this forum. Consult the PHP documentation for further assistance.

If it's no longer being used anymore and using StackOverflow instead, can we update the README file already.

**Comment by ildar** [comment]
https://gitter.im/nfc-tools/libfreefare is good?
