### ISSUE TITLE
Device not supported?

### ISSUE THREAD

**Issue by Deph0** [nfc-tools/libnfc#411]
Hello, i recently got the ownership of a hid global omnikey 6321, and want to use it for a project that uses libnfc. seeing as i am using a mac, i downloaded libnfc with brew. and got the pc/sc drivers in order.. nfc-list came up empty again and again, so i found the env log-level to make nfc-list give me more info and found this.
```
$ LIBNFC_LOG_LEVEL=3 nfc-list
debug	libnfc.config	key: [allow_intrusive_scan], value: [yes]
debug	libnfc.config	Unable to open directory: /usr/local/Cellar/libnfc/1.7.1/etc/nfc/devices.d
debug	libnfc.general	log_level is set to 3
debug	libnfc.general	allow_autoscan is set to true
debug	libnfc.general	allow_intrusive_scan is set to true
debug	libnfc.general	0 device(s) defined by user
nfc-list uses libnfc 1.7.1
debug	libnfc.general	0 device(s) found using arygon driver
debug	libnfc.general	0 device(s) found using pn532_uart driver
debug	libnfc.general	0 device(s) found using ACR122S driver
debug	libnfc.general	0 device(s) found using acr122_usb driver
debug	libnfc.driver.acr122_pcsc	PCSC device [OMNIKEY CardMan (076B:6321) 6321(1)] is not NFC capable or not supported by libnfc.
debug	libnfc.driver.acr122_pcsc	PCSC device [OMNIKEY CardMan (076B:6321) 6321(2)] is not NFC capable or not supported by libnfc.
debug	libnfc.general	0 device(s) found using acr122_pcsc driver
debug	libnfc.general	0 device(s) found using pn53x_usb driver
No NFC device found.
```

so my question is, why isn't it supported? i was under the impression that all pc/sc was supported.

**Comment by doegox** [comment]
> i was under the impression that all pc/sc was supported.

I don't know from where you got such impression but only some specific readers are supported, all based on PN53x chips: http://nfc-tools.org/index.php?title=Devices_compatibility_matrix
