### ISSUE TITLE
"INSTALL" file does not exist

### ISSUE THREAD

**Issue by anik786** [nfc-tools/libnfc#414]
In the README file it says:

> See the file INSTALL for configure, build and install details.

however I could not find a file called INSTALL. Does it exist?

**Comment by ipv6freely** [comment]
Hard to use without knowing how to install.

**Comment by kmoe** [comment]
This confused me too (https://github.com/nfc-tools/libnfc/issues/333). Clone the repo and run `autoreconf -is`.

**Comment by LudovicRousseau** [comment]
See https://github.com/nfc-tools/libnfc/issues/593
