### ISSUE TITLE
Libtool Version problem.

### ISSUE THREAD

**Issue by fjms** [nfc-tools/libnfc#415]
` CC       libnfcchips_la-pn53x.lo
libtool: Version mismatch error.  This is libtool 2.4.6 Debian-2.4.6-0.1, but the
libtool: definition of this LT_INIT comes from libtool 2.4.2.
libtool: You should recreate aclocal.m4 with macros from libtool 2.4.6 Debian-2.4.6-0.1
libtool: and run autoconf again.`

How can I correct this error?

Thanks

**Comment by doegox** [comment]
Which version are you trying to compile?
I advise you to try the current git head instead and start with `autoreconf -vis`

**Comment by fjms** [comment]
1.7.1 release.
Ok, I'm going to try that.

**Comment by fjms** [comment]
Nice, it worked perfect
