### ISSUE TITLE
make libnfc open my app with an argument

### ISSUE THREAD

**Issue by Ali-Reza8** [nfc-tools/libnfc#422]
Hi,

I tried "nfc-emulate-forum-tag4" and on phone it opened browser and then nfc-tools.org

when I checked the source code, both app and url were written in hex,
and I couldn't figure it out how it worked

now, I want to open my android app with an argument(such as hello).

how should I do this?

thanks

**Comment by doegox** [comment]
not related to development of this project I'm afraid. Feel free to ask over https://discord.com/invite/2Y8tRNa94G
