### ISSUE TITLE
Libnfc command on kali

### ISSUE THREAD

**Issue by jordanmv1c** [nfc-tools/libnfc#427]
nfc-list show all the device that connected
Witch more command are usefull?
I want the command that i can type on terminal to read data from card

**Comment by gyx99** [comment]
i use mfoc to read and use nfc-mfclassic to wirte(i can also write)

**Comment by jordanmv1c** [comment]
@gyx99 could you please explain more?
Can you write here the command you type on the terminal??

(By the way how do you use it? You wrap it with gui?c#?)

Thank

**Comment by gyx99** [comment]
i only have used mfoc to crack m1 card (with pn532)，i dont have other card to try
conmand: nfc-mfclassic r a new.dump old.dump
can read card with a current data file(old.dump) but you didnt crack it 
maybe you can ask the author of mfoc about your card
or maybe your card is security ,People can not crack him now
