### ISSUE TITLE
Use acr122u reader withour wrapper

### ISSUE THREAD

**Issue by Sharganov** [nfc-tools/libnfc#434]
Hello, 

I tried to build simple app which uses libnfc, configured and build for acr122_pcsc driver and got 

`/usr/local/lib/libnfc.a(libnfcdrivers_la-acr122_pcsc.o): In function 'acr122_pcsc_receive':
/home/pi/workspace/lib/libnfc-libnfc-1.7.1/libnfc/drivers/acr122_pcsc.c:413: undefined reference to 'SCardTransmit'
.....
`

Then I found out that examples are started from wrapper. What is a reason to use wrapper? If it possible to run smth without it?

Thanks.

**Comment by doegox** [comment]
sounds like you were missing linking with pcsclite libraries
