### ISSUE TITLE
can't read NMT_ISO14443B2SR card

### ISSUE THREAD

**Issue by Joni1987** [nfc-tools/libnfc#437]
I Done exactly like https://github.com/nfc-tools/libnfc/blob/master/examples/doc/quick_start_example1.c
replace `NMT_ISO14443A `with `NMT_ISO14443B2SR`  but i can't read the card.

1-on witch card do you check NMT_ISO14443B2SR type?
2-witch reader (that working with libnfc) support to read card like NMT_ISO14443B2SR?,
3- is it impossible that reader can read ISO14443B but can't read ISO14443B2SR ??

**Comment by doegox** [comment]
See issue #436
