### ISSUE TITLE
Which Pn532 module ? 

### ISSUE THREAD

**Issue by aminmrp** [nfc-tools/libnfc#438]
Hi ...
i have question ... In libnfc ,There is a driver for PN532 module. Is this driver for the NXP version of this module or Adafruit version?If this driver is for Adafruit module , can i use it for NXP module?
(Red module is NXP version and blue module is adafruit version )
Thank you for your attention

![pn532 1 -350x350](https://user-images.githubusercontent.com/31317143/29982679-ecdf5eb8-8f67-11e7-8430-30fb3e41ecc1.jpg)
![364-05](https://user-images.githubusercontent.com/31317143/29982686-f4312002-8f67-11e7-88c1-0fd2fa3d3473.jpg)

**Comment by doegox** [comment]
Drivers talk directly to the PN532 chip so both board will work.
But beware antenna performance may vary a lot.
Antenna of Adafruit is very good (and there are 15$ clones of that one that work equally well).

**Comment by aminmrp** [comment]
The NXP module has (I2C , SPI and UART ) . which is the best ? Which is easier to work with?

**Comment by doegox** [comment]
They're all good.
It depends on what you want to connect it to.
E.g. for a laptop, UART with a USB-Serial cable is the esiest.
E.g. for a RPi, I2C or SPI on its GPIO port are the easiest.

**Comment by aminmrp** [comment]
@doegox Oh sir ... If I want to connect it with SPI to Libnfc, does Libnfc know it as PN532 module or RPi?

**Comment by aminmrp** [comment]
@doegox Does the library recognize the NXP PN532 automatically on a laptop??? I use kali linux

**Comment by aminmrp** [comment]
@doegox  Oh sir ... i have a more question 😅 if i wanna connect NXP PN532 module to laptop (UART mode), Is there a special cable for connecting it?

**Comment by doegox** [comment]
any usb-uart cable should work.
just make sure it's recognized by linux but most cables are.

**Comment by doegox** [comment]
to get the board recognized over USB-UART, you've to edit libnfc.conf, see last lines of

https://github.com/nfc-tools/libnfc/blob/master/libnfc.conf.sample
