### ISSUE TITLE
C# bindings : Device's internal chip error

### ISSUE THREAD

**Issue by MaitreDede** [nfc-tools/libnfc#464]
Hi,
I am trying to write binding for C#, and when I try to poll for a target as initiator, the poll method returns me an error -90 `Device's internal chip error`.
If I call `nfc_device_get_last_error` after trying to poll, the result value is `Success`.
The debug log has not given me any clue.

The device is a PN532 plugged on I2C of a Raspberry Pi 3. The original `nfc-poll` is working like a charm.
Using distrib version of libnfc, `nfc_version` returns 1.7.1. Device info :
```
chip: PN532 v1.6
initator mode modulations: ISO/IEC 14443A (106 kbps), FeliCa (424 kbps, 212 kbps), ISO/IEC 14443-4B (106 kbps), Innovision Jewel (106 kbps), D.E.P. (424 kbps, 212 kbps, 106 kbps)
target mode modulations: ISO/IEC 14443A (106 kbps), FeliCa (424 kbps, 212 kbps), D.E.P. (424 kbps, 212 kbps, 106 kbps)
```

**Comment by doegox** [comment]
not related to development of this project I'm afraid. Feel free to ask over https://discord.com/invite/2Y8tRNa94G
