### ISSUE TITLE
 [Error] nfc/nfc.h: No such file or directory

### ISSUE THREAD

**Issue by ElixG** [nfc-tools/libnfc#473]
Hi guys i just started working with libnfc and the compiler gives me this error while trying to compile "[Error] nfc/nfc.h: No such file or directory", can you guys help me? did i fail libnfc installation?

**Comment by aminmrp** [comment]
@ElixG  Hi , when do you see this error ? At what stage? If you see this error when you test the code `./configure `, use this code :  `autoreconf -Wall -vis`  then use `./configure`

**Comment by SloCompTech** [comment]
@ElixG Hi,
I installed libnfc with folowing commands
```
git clone https://github.com/nfc-tools/libnfc.git
cd libnfc
autoreconf -vis
./configure --prefix=/usr --sysconfdir=/etc
make
sudo make install
sudo cp libnfc.conf.sample /etc/nfc/libnfc.conf # Here I added my reader
```
Compling should work with `-lnfc` flag. Else you can add manualy include dir with `-I <incdir>`.

Cheers

**Comment by neomilium** [comment]
Thanks @SloCompTech for reply!
