### ISSUE TITLE
Unable to claim USB interface (Device or resource busy) Acr122

### ISSUE THREAD

**Issue by C1ta** [nfc-tools/libnfc#475]
Writing nfc-list answers me with this error
`error libnfc.driver.acr122.usb Unable to claim USB interface (Device or resource busy)`

How i fix this problem? Thanks

**Comment by stawiski** [comment]
Did you build nfc-list as root?
Try sudo.

**Comment by nospam2000** [comment]
> Device or resource busy

This error message normally means, that some other daemon is already using the device. The command fuser -fu /dev/YOUR_PORT can help you detect such a daemon.

On my Mac i have the problem, that it has a daemon which claims the acr122, so it cannot be used by libnfc. If you have the same problem, then you can disable the daemon.

**Comment by AdamLaurie** [comment]
$ cat /etc/modprobe.d/blacklist-libnfc.conf
blacklist nfc
blacklist pn533
