### ISSUE TITLE
Makefile not created with the doc

### ISSUE THREAD

**Issue by Aarbel** [nfc-tools/libnfc#484]
Cf the doc : http://nfc-tools.org/index.php?title=Libnfc:Arduino

```
autoreconf -vis
./configure --with-drivers=pn532_uart --sysconfdir=/etc --prefix=/usr
make clean all
```
Error `make: *** No rule to make target `clean'. Stop.`

The makefile isn't created, that's why the make command don't work.
Do you know a solution ? :)

**Comment by LudovicRousseau** [comment]
The `Makefile` file is not created because `./configure` failed.
You need to fix that first.
