### ISSUE TITLE
libnfc.driver.pn532_uart  error on ACR122U

### ISSUE THREAD

**Issue by VitaKiyanova** [nfc-tools/libnfc#486]
i installed libnfc 1.7.0 on RPi raspbian jessie. 
nfc-poll is not working,
 this is error text:

> error libnfc.driver.pn532_uart                                                       pn53x_check_communication error
 nfc-poll: ERROR: Unable to open NFC device

Thanks in advance

i am using ACR122U

**Comment by ChunJyeBehBeh** [comment]
Hello,

May I know how you solve it?

I have the following error also after I run the command `sudo ./nfc-poll` :
```
/home/pi/libnfc/libnfc-1.7.0/examples/.libs/lt-nfc-poll uses libnfc 1.7.0
pn53x_check_communication: Timeout
lt-nfc-poll: ERROR: Unable to open NFC device.
```
