### ISSUE TITLE
Add Support for ThinkPad X280 (NXP)

### ISSUE THREAD

**Issue by spielkind** [nfc-tools/libnfc#497]
Unfortunately I have no idea which device exactly is build into the ThinkPad x280.
Regarding docs, it's an NXP device.

Let me know how I can add more data.

> i2c-3	i2c       	DPDDC-A                         	I2C adapter
> i2c-1	i2c       	i915 gmbus dpb                  	I2C adapter
> i2c-6	i2c       	Synopsys DesignWare I2C adapter 	I2C adapter
> i2c-4	i2c       	DPDDC-B                         	I2C adapter
> i2c-2	i2c       	i915 gmbus dpd                  	I2C adapter
> i2c-0	i2c       	i915 gmbus dpc                  	I2C adapter
> i2c-7	smbus     	SMBus I801 adapter at efa0      	SMBus adapter
> i2c-5	i2c       	DPDDC-C                         	I2C adapter

**Comment by neomilium** [comment]
PR is welcome.
