### ISSUE TITLE
Raspberry Pi: Are there any command line tool to wait/read/write to cards using nfclib?

### ISSUE THREAD

**Issue by ertankucukoglu** [nfc-tools/libnfc#529]
Hello,

I am on Raspberry Pi. Using PN532 from "elechouse nfc module v3". It is on I2C mode and I can do nfc-poll and see it reading tag.

I need to develop application but, I have very limited C knowledge. I am planning on using Lazarus. No available library codes for Lazarus that I could find.

I decided to call a command within lazarus application and parse output to manipulate module. My searches I failed to find any such tool.

I am trying here as last resort.

Any help is appreciated.

Thanks & regards,
Ertan

**Comment by doegox** [comment]
not related to development of this project I'm afraid. Feel free to ask over https://discord.com/invite/2Y8tRNa94G
