### ISSUE TITLE
any plan for a Libnfc release 1.7.2?

### ISSUE THREAD

**Issue by LudovicRousseau** [nfc-tools/libnfc#537]
libnfc 1.7.1 was released in May 2015. 
Any plan for a new release?

**Comment by graynk** [comment]
Honestly I'm kind of amazed that there's been so much work done, but there had been no release since 2015. This should not be a question of 'if', rather it should be 'when'.

**Comment by fuzxxl** [comment]
Indeed.  As noted in #596, the lack of new releases has already pretty much stalled development of other libraries down the road as they cannot depend on features that are only present in unpublished versions of the library.

Please cut a release some time, even if it isn't perfect!

**Comment by doegox** [comment]
done :)
