### ISSUE TITLE
Pn532 RF Transmission Error" (-20)

### ISSUE THREAD

**Issue by MaxMaxov93** [nfc-tools/libnfc#550]
Hello. I'm faced with a problem. I'm trying to use nfc-list command and a log level 3 and it throws an error:
debug	libnfc.chip.pn53x	Chip error: "Timeout" (01), returned error: "RF Transmission Error" (-20))
I'm using Kali and a new pn532. Is it a hardware issue? Thanks in advance.

**Comment by MaxMaxov93** [comment]
Full log
[nfclist-log.txt](https://github.com/nfc-tools/libnfc/files/3453432/nfclist-log.txt)

**Comment by scottaric** [comment]
@MaxMaxov93 I'm having the same issue with a Pi 4 Model B.  Did you ever find a solution?

**Comment by MaxMaxov93** [comment]
@scottaric in my case it happened to be that the device was broken. Then I bought and tested three more brand new ones (for different purposes) and everything was working correctly.

**Comment by yellowzq** [comment]
Can you tell me what device are you using?

**Comment by yellowzq** [comment]
I had the same problem with it.
I use the Acr122U to relay.

**Comment by ld21** [comment]
I'm having the same issue (debug	libnfc.chip.pn53x	Chip error: "Timeout" (01), returned error: "RF Transmission Error" (-20))) when trying to use nfc-mfclassic w a dump.mfd using one of adafruits PN532 boards [https://www.adafruit.com/product/364](url). Is there another idea what could be wrong other than it is broken? (I can perfectly read nfc cards with the device).
