### ISSUE TITLE
ThinkPad Yoga X1 3rd Gen: No NFC device found.

### ISSUE THREAD

**Issue by Noxmiles** [nfc-tools/libnfc#552]
The Lenovo ThinkPad Yoga X1 3rd Gen / 2018 has an NFC Device, which is not recogniced by libnfc. I know that the device is an NXP NFC Reader. Sadly I have no /dev/i2c entrys, so I could not use i2cdetect.

For Windows there are these 2 drivers required (Link 1)
- NXP NFC Driver (NxpNfcClientDriver) which requires:
- Intel Serial IO Driver for the GPIO & I2C Host Controller

Both drivers are also for the P52s and the T580.

1: https://pcsupport.lenovo.com/de/de/products/laptops-and-netbooks/thinkpad-x-series-laptops/thinkpad-x1-yoga-3rd-gen-type-20ld-20le-20lf-20lg/downloads

**Comment by neomilium** [comment]
This device is not supported.
PR is welcome.
