### ISSUE TITLE
Detect mifare ultralight card with wrong BCC

### ISSUE THREAD

**Issue by target111** [nfc-tools/libnfc#555]
Is there any way libnfc could allow for reading tags with a wrong bcc? I accidentally bricked my ultralight chinese uid changeable card and I'm looking for a way to fix it.

**Comment by neomilium** [comment]
Not enough details to reply. Sorry…

**Comment by target111** [comment]
I've accidentally written ffffffff to the first 4 bytes of the UID of a mifare ultralight card and now it's unreadable. I was wondering if libnfc could help me recover it.

**Comment by doegox** [comment]
fyi it's doable on proxmark3 https://github.com/RfidResearchGroup/proxmark3/blob/master/doc/magic_cards_notes.md#proxmark3-commands-5
Feel free to ask help over https://discord.com/invite/2Y8tRNa94G
