### ISSUE TITLE
PN532 Firmware 1.4 ?

### ISSUE THREAD

**Issue by tech-ozon-io** [nfc-tools/libnfc#557]
Hi,

I bought a PN532 module with firmware 1.4. It not work with my mifare card. I use serial COM to 115200 bauds.

   https://fr.aliexpress.com/item/32718408514.html
   https://fr.aliexpress.com/item/32970730027.html

I own another PN532 with direct usb port (ACR122U)

   https://fr.aliexpress.com/item/33061586229.html

I work and it can read my card.

The only one difference between the PN532 are the firmware. The working one is 1.6, the other is 1.4. I exclude communication problem between the device and my computer, I sniff RS232 communication and bytes exchange is conform to the PN532 user manual. I also test the excitation of the antenna with my oscilloscope. It is excited (but I can't validate frequency nor nor protocol because my scope is a little bit old and low cost).

Maybe the 1.4 firmware have some known bugs ? or it is not supported by libnfc ?

Thanks
Thierry

**Comment by neomilium** [comment]
AFAIR, there is restriction in `libnfc` based on firmware. Please provide more details (e.g. debug traces) and reopen the issue if relevant.
