### ISSUE TITLE
Website not working

### ISSUE THREAD

**Issue by stigok** [nfc-tools/libnfc#558]
The website https://nfc-tools.org has not been working for at least some weeks now.

**Comment by smortex** [comment]
@doegox @neomilium do you know if Roel is still managing this domain?  (also libnfc.org redirects to this broken domain).

**Comment by doegox** [comment]
no idea :(

**Comment by neomilium** [comment]
@smortex it was Roel who manage libnfc.org and nfc-tools.org. I haven't be noticed of a change.

**Comment by doegox** [comment]
I sent him a mail on his professional address, let's see...

**Comment by peternewman** [comment]
In the short term, Web Archive has it:
http://web.archive.org/web/20190723132538/http://nfc-tools.org/index.php/Main_Page

**Comment by darconeous** [comment]
Does it really make sense to have a mediawiki setup? I would think just having a static page (<https://github.com/nfc-tools/nfc-tools.github.io> perhaps?) for info and generated documentation would be sufficient, and use the built-in github wiki support instead.

**Comment by doegox** [comment]
yes we should try to extract the source of wiki pages on archive.org and transfer them to the github wiki of the project

**Comment by darconeous** [comment]
I'm guessing Roel is MIA?

**Comment by doegox** [comment]
I didn't get any reply indeed

**Comment by darconeous** [comment]
Does he control the domain registrations as well?

**Comment by doegox** [comment]
yes

**Comment by doegox** [comment]
this evening we got news from Roel :)
So the website is back:
http://nfc-tools.org/index.php?title=Main_Page
and in the process of getting back access to it, I fixed the forum as well:
http://forums.nfc-tools.org/

**Comment by doegox** [comment]
thanks @neomilium , you had better success than I reaching Roel ;)

**Comment by smortex** [comment]
Hooray!  Thanks for handling this, I think we can close this now :wink:
