### ISSUE TITLE
UID in 8H10D format

### ISSUE THREAD

**Issue by maltitco** [nfc-tools/libnfc#565]
How to get the UID of the card in 8H10D format?

For example:
Original EM tag UID (Hex): 10 00 62 D9 B2
8H10D conversion rule: take last eight hexadecimal digits, 00 62 D9 B2, convert it to 10 decimal digits.
Hexadecimal 0062D9B2 = Decimal 6478258
So its 8H10D format is: 0006478258

**Comment by yesIamFaded** [comment]
no.

**Comment by doegox** [comment]
not related to development of this project I'm afraid. Feel free to ask over https://discord.com/invite/2Y8tRNa94G
