### ISSUE TITLE
can someone help me when i configure libirecovery i get this error

### ISSUE THREAD

**Issue by shawn7226791** [nfc-tools/libnfc#571]
./configure: line 6664: syntax error near unexpected token `libusb,'
./configure: line 6664: `			PKG_CHECK_MODULES(libusb, libusb-1.0 >= $LIBUSB_VERSION)'

**Comment by mkapln2** [comment]
same

**Comment by thekix** [comment]
Hi,

nfc-tools uses libusb to connect with the devices. You need include libusb (devel files) in your system to compile nfc-tools.

For example, in debian/ubuntu you can do it using:

apt-get install libusb-dev

Regards,
kix

**Comment by thekix** [comment]
@mkapln2 @shawn7226791 if the problem is solved, please, close the bug.

Regards,
kix

**Comment by neomilium** [comment]
@thekix Thanks for your help.
No reply from author, closing issue.
