### ISSUE TITLE
Any hints on some writing issues?

### ISSUE THREAD

**Issue by jpadie** [nfc-tools/libnfc#572]
I have a couple of tags that I want to clone (uid and contents).  I can access the keys and data on each. 

however when I try to write them to blank cards I find that for one tag only 60/64 blocks are written and on the other only the first four blocks are written although in the latter case the tool reports that all 64 blocks are successfully written.

the dumps are done with mfoc.  the process is:

mfoc -O cardToBeCloned.dmp -kxxxxxxxxxxxx
mfoc -O blankCard.dmp
nfc-mfclassic W a u ./cardToBeCloned.dmp ./blankCard.dmp 
mfoc -O clonedCard.dmp 

i'm using blank supposedly UID rewritable cards from Amazon.  the UID is successfully rewritten in the process on all the cards; the dumps confirm this.  

can anyone set me on a path to determining or debugging _why_ the cards are not being faithfully written?  

I've tried thirty.  from two different sources online.  they are all rewritten the same; except one which is an exact replica.  

I'm using libnfc-1.7.1-223-gf8b2852 on a linux distro.  I've removed the apt versions of the tools and reinstalled from source.  

thanks in advance!

**Comment by doegox** [comment]
not related to development of this project I'm afraid. Feel free to ask over https://discord.com/invite/2Y8tRNa94G
