### ISSUE TITLE
nfc-list Frame header mismatch

### ISSUE THREAD

**Issue by mimta** [nfc-tools/libnfc#573]
Hi,
I installed the nfc on Virtual Box and Ubuntu 18.04.  but I get this error! any solution?  

nfc-list uses libnfc 1.7.1
error	libnfc.driver.acr122_usb	Frame header mismatch
error	libnfc.driver.acr122_usb	PN532 init failed, trying again...
error	libnfc.driver.acr122_usb	Frame header mismatch
error	libnfc.driver.acr122_usb	PN532 init failed, trying again...
error	libnfc.driver.acr122_usb	Frame header mismatch
nfc-list: ERROR: Unable to open NFC device: acr122_usb:001:003

Thanks

**Comment by neomilium** [comment]
Turn on the debug output after a careful read of README file.
