### ISSUE TITLE
INSTALL.md inside gitignore and no longer in the repo

### ISSUE THREAD

**Issue by justingiffard** [nfc-tools/libnfc#575]
INSTALL no longer present in repo

**Comment by LudovicRousseau** [comment]
See https://github.com/nfc-tools/libnfc/issues/593

**Comment by LudovicRousseau** [comment]
duplicate.

**Comment by justingiffard** [comment]
Look at the issue number... mine was firs therefore #593 is a duplicate of mine (#575). Not to mention this bug was opened 6 months ago. No comment

**Comment by LudovicRousseau** [comment]
I know. I am not the maintainer of this project. I just try to help.

Note that it is not really a duplicate. You mention `INSTALL.md` and the other issue mentions `INSTALL`.
