### ISSUE TITLE
build with LIBNFC_DRIVER_ARC122_USB issue

### ISSUE THREAD

**Issue by VmFree** [nfc-tools/libnfc#577]
current build script can't build with option LIBNFC_DRIVER_ARC122_USB, due to follow issue:
IF(LIBNFC_DRIVER_ACR122_USB)
  FIND_PACKAGE(LIBUSB REQUIRED)
  ADD_DEFINITIONS("-DDRIVER_ACR122_USB_ENABLED")
  SET(DRIVERS_SOURCES ${DRIVERS_SOURCES} "drivers/acr122_usb")
  SET(USB_REQUIRED TRUE) ## **forgot set USB_REQUIRED as TRUE**
ENDIF(LIBNFC_DRIVER_ACR122_USB)

**Comment by neomilium** [comment]
PR is welcome.
