### ISSUE TITLE
nfc_open failed for acr122_pcsc

### ISSUE THREAD

**Issue by VmFree** [nfc-tools/libnfc#578]
Hi all, the problem is :

E:\java-prj\build-nfc\install>nfc-scan-device.exe
info    libnfc.config   Unable to open file: E:java-pruild-nfclibnfcbuildconfig/libnfc.conf
debug   libnfc.config   Unable to open directory: E:java-pruild-nfclibnfcbuildconfig/devices.d
unknown libnfc.general  log_level is set to 3
debug   libnfc.general  allow_autoscan is set to true
debug   libnfc.general  allow_intrusive_scan is set to true
debug   libnfc.general  0 device(s) defined by user
nfc-scan-device.exe uses libnfc 1.7.1
debug   libnfc.general  0 device(s) found using arygon driver
debug   libnfc.general  0 device(s) found using pn532_uart driver
debug   libnfc.general  0 device(s) found using ACR122S driver
debug   libnfc.general  0 device(s) found using acr122_usb driver
debug   libnfc.general  1 device(s) found using acr122_pcsc driver
debug   libnfc.general  0 device(s) found using pn53x_usb driver
1 NFC device(s) found:
debug   libnfc.driver.acr122_pcsc       Attempt to open ACS ACR122 0
debug   libnfc.general  Unable to open "acr122_pcsc:ACS ACR122 0".
nfc_open failed for acr122_pcsc:ACS ACR122 0

my env is win7 x64, libnfc-1.7.1. completely no idea....

**Comment by geeto** [comment]
I am having the exact same problem. Any luck?
