### ISSUE TITLE
I need help with mifare authentication

### ISSUE THREAD

**Issue by TrixyCracker** [nfc-tools/libnfc#581]
Hello, i really need help, i don't know what to do to authenticate a mifare classic 1k card. I send the command 0x60-0x03-crc-crc and the card send the token RB. Now what i have to do for calculate token AB and successively decrypt token BA?
Thanks in advance.

**Comment by FeitianSmartcardReader** [comment]
which reader are you using?

**Comment by xGabbro** [comment]
> 
> 
> which reader are you using?

pn532

**Comment by doegox** [comment]
not related to development of this project I'm afraid. Feel free to ask over https://discord.com/invite/2Y8tRNa94G
