### ISSUE TITLE
NFC Tag mode on raspberry pi

### ISSUE THREAD

**Issue by SangsubLim** [nfc-tools/libnfc#585]
What I want is raspberry pi to act as NFC Tag, like a credit card.
When I touch the NFC module on the raspberry pi with the Android phone, a particular app is executed (such as YouTube, for example).

my development environment is as follows.
- LG V30
- raspberry pi 3 B
- raspbian : 2019-07-10-raspbian-buster-lite
- NFC : PN532 module (https://www.sunfounder.com/pn532-nfc-module-for-raspberry-pi.html)

I've wired the raspberry pi and PN532 Module with i2c and proceeded according to the guide below.

http://wiki.sunfounder.cc/index.php?title=PN532_NFC_Module_for_Raspberry_Pi

I performed nfc-pool as in the guide above, and it worked well when I contacted my credit card.
But I'm trying to get my raspberry pi to work with an NFC Tag like a credit card.

So I tried doing nfc-emulate-tag among the samples provided by libnfc.
As a result, the following error occurred.

pi@raspberrypi:/proc $ nfc-emulate-tag
nfc-emulate-tag uses libnfc libnfc-1.7.1-223-gf8b2852
NFC device: _PN532_I2c opened
nfc-emulate-tag will emulate this ISO14443-A tag:
ISO/IEC 14443A (undefined baud rate) target:
    ATQA (SENS_RES): 00  04
* UID size: single
* bit frame anticollision supported
       UID (NFCID3): 08  ab  cd  ef
* Random UID
      SAK (SEL_RES): 09
* Not compliant with ISO/IEC 14443-4
* Not compliant with ISO/IEC 18092

Fingerprinting based on MIFARE type Identification Procedure:
* MIFARE Mini 0.3K
* SmartMX with MIFARE 1K emulation
Other possible matches based on ATQA & SAK values:
NFC device (configured as target) is now emulating the tag, please touch it with a second NFC device (initiator)
error   libnfc.bus.i2c  Error: read only -1 bytes (265 expected) (Input/output error).
nfc_target_init: Success
nfc_target_emulate_tag: Success
error   libnfc.bus.i2c  Error: wrote only -1 bytes (10 expected) (Input/output error).
error   libnfc.driver.pn532_i2c Failed to transmit data. Retries left: 2.
error   libnfc.bus.i2c  Error: wrote only -1 bytes (10 expected) (Input/output error).
error   libnfc.driver.pn532_i2c Failed to transmit data. Retries left: 1.
error   libnfc.bus.i2c  Error: wrote only -1 bytes (10 expected) (Input/output error).
error   libnfc.driver.pn532_i2c Failed to transmit data. Retries left: 0.
error   libnfc.driver.pn532_i2c Unable to transmit data. (TX)

Then my PN532 module wend dead.

I checked where the error came from and it's happening in "nfc_target_init.
This function is described as "Initialize NFC device as an emulated tag."

I am looking for anyone who has tried NFC Tag using raspberry pi with PN532 or anyone who can advise me about this situation.
Thank you.

**Comment by neomilium** [comment]
Please read man pages of these examples, there are information there.
