### ISSUE TITLE
Memory leakage

### ISSUE THREAD

**Issue by AbuLSim** [nfc-tools/libnfc#592]
Running **Valgrind** on **nfc-anticol** tool or any other function that calls **nfc_open** function ends up with 48 bytes of memory leakage (even if **nfc_close** function was called) coming from:

==3001== 48 bytes in 1 blocks are definitely lost in loss record 3 of 11
==3001==    at 0x4C2DB8F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==3001==    by 0x542B93D: usb_parse_configuration (in /lib/x86_64-linux-gnu/libusb-0.1.so.4.4.4)
==3001==    by 0x542D51C: usb_os_find_devices (in /lib/x86_64-linux-gnu/libusb-0.1.so.4.4.4)
==3001==    by 0x542AB6F: usb_find_devices (in /lib/x86_64-linux-gnu/libusb-0.1.so.4.4.4)
==3001==    by 0x4E4B7BA: usb_prepare (usbbus.c:73)
==3001==    by 0x4E4C4F4: acr122_usb_open (acr122_usb.c:400)
==3001==    by 0x4E406A6: nfc_open (nfc.c:269)
==3001==    by 0x400CAD: main (nfc-anticol.c:188)

The description above was found by running :

**valgrind --leak-check=full nfc-anticol**

One can check more details with
**valgrind --leak-check=full --show-leak-kinds=all nfc-anticol**

**Comment by smortex** [comment]
It's a known issue in libnfc
