### ISSUE TITLE
Missing shared libraries after install

### ISSUE THREAD

**Issue by xLinkOut** [nfc-tools/libnfc#615]
After installing `libnfc` by downloading it from the [release page](https://github.com/nfc-tools/libnfc/releases/tag/libnfc-1.8.0),
none of the installed software works, showing the following error:

> nfc-poll: error while loading shared libraries: libnfc.so.6: cannot open shared object file: No such file or directory

This seems to fix the problem [source](https://oneguyoneblog.com/2015/09/16/acr122u-nfc-usb-reader-raspberry-pi/) :
```bash
sudo sh -c "echo /usr/local/lib > /etc/ld.so.conf.d/usr-local-lib.conf"
sudo ldconfig
```
This happens even with 1.7.0, 1.7.1 and 1.8.0.

**Comment by romain145** [comment]
Issue and fix confirmed with https://github.com/nfc-tools/libnfc/commit/c3f739dea339a71c59d7d53ab6b0ecc477c3ab73

**Comment by stanx89** [comment]
> After installing `libnfc` by downloading it from the [release page](https://github.com/nfc-tools/libnfc/releases/tag/libnfc-1.8.0),
> none of the installed software works, showing the following error:
> 
> > nfc-poll: error while loading shared libraries: libnfc.so.6: cannot open shared object file: No such file or directory
> 
> This seems to fix the problem [source](https://oneguyoneblog.com/2015/09/16/acr122u-nfc-usb-reader-raspberry-pi/) :
> 
> ```shell
> sudo sh -c "echo /usr/local/lib > /etc/ld.so.conf.d/usr-local-lib.conf"
> sudo ldconfig
> ```
> 
> This happens even with 1.7.0, 1.7.1 and 1.8.0.

Was stuck with similar thing, this helped..
