### ISSUE TITLE
Mfoc

### ISSUE THREAD

**Issue by patapouff** [nfc-tools/libnfc#619]
*-
* Free/Libre Near Field Communication (NFC) library
*
* Libnfc historical contributors:
* Copyright (C) 2009      Roel Verdult
* Copyright (C) 2009-2015 Romuald Conty
* Copyright (C) 2010-2012 Romain Tartière
* Copyright (C) 2010-2013 Philippe Teuwen
* Copyright (C) 2012-2013 Ludovic Rousseau
* Additional contributors:
* See AUTHORS file
-*

**Comment by patapouff** [comment]
https://github.com/nfc-tools/libnfc/issues/619#issue-671779938

**Comment by doegox** [comment]
?

**Comment by patapouff** [comment]
https://github.com/nfc-tools/libnfc/issues/619#issue-671779938
