### ISSUE TITLE
how to lock ufuid card with nfc-mfsetuid?

### ISSUE THREAD

**Issue by vagile-cn** [nfc-tools/libnfc#623]
I find many version of nfc-mfsetuid that have a parameter " -l ".
This parameter can lock ufuid card. but it's only on windows.
I don't find any information whit this parameter and I can't find any help on any where 
![image](https://user-images.githubusercontent.com/22270643/95932483-8c33ee80-0dfe-11eb-88b2-fae531bdb580.png)
who can tell me  how do this with libnfc and PN532

**Comment by doegox** [comment]
it's not part of this repo. If you get the sources of these forks this could be merged.
