### ISSUE TITLE
Change readme configuration section

### ISSUE THREAD

**Issue by danieleongaro** [nfc-tools/libnfc#648]
I don't know if i'm reporting this in the correct way. The readme says to save the file libnfc.conf in the folder /etc/nfc however, after a bit of troubleshooting i found that the software searches the config file in another directory. This is also confirmed by looking at the configure file, the default position where the software will search for the configuration file is /usr/local/etc/nfc/libnfc.conf
This should be changed in the readme.

**Comment by neomilium** [comment]
The configuration file `libnfc.conf` is placed in `nfc/` subdirectory of the `confdir` .
`confdir` is set during build configuration step (ie. `./configure`).

BTW, if you want to explain this in README, feel free to provide a PR with patches.
