### ISSUE TITLE
Please add support for native Linux NFC interface (via NetLink)

### ISSUE THREAD

**Issue by arbv** [nfc-tools/libnfc#674]
There was a similar issue closed some time ego (#466), but I think that this issue needs to be reevaluated to support cases like #455 (Lenovo T470) and for many more modern laptops (like mine HP ZBook Firefly 14 G8), which happens to have an NFC chip available and usable via Netlink interface (e.g. via `nfctool`) but not by any software which uses `libnfc` to access an NFC interface (like `pcsclite`).

Sure thing, such a driver would be not cross platform, but on Linux it may cover many devices in a unified way.

For example,  support for native Linux NFC was added to `libfido2`  for a similar reason to support NFC pasword-less authentication tokens (e.g. Yubikeys), these devices can act as contactless smart-cards as well, but often not on Linux, due to lack of native Linux NFC support in `libnfc`.

**Comment by DaClemens** [comment]
I can only second this. That aside, if someone could give me some pointers on where to start and some rough steps, I am willing to try my hands and contribute, but I'm new to this project.

**Comment by agorgl** [comment]
Would love to see this too!

**Comment by neomilium** [comment]
Feel free to provide some PR with patches to support these devices!
