### ISSUE TITLE
Driver for MRFC522 ic

### ISSUE THREAD

**Issue by danielfranzini-dock** [nfc-tools/libnfc#681]
Hello! Is a driver for MRFC522 IC from NXP desirable? I'm an embedded systems engineer and I'm willing to implement the missing bits if anyone is willing to provide some guidance.

The current setup I have is an Arduino Nano connected to a RC522 module (wich in turn, uses a MRFC522 IC). Most likely I'll have to implement some sort of pass-through interface from the Arduino to the module but that does not seems to be a big problem.

Thanks in advance.

**Comment by ildar** [comment]
Dup of https://github.com/nfc-tools/libnfc/issues/523#issuecomment-754201795

**Comment by AmikadM** [comment]
Any update on this ?
