### ISSUE TITLE
Makefile missing separator error

### ISSUE THREAD

**Issue by MyriamAA** [nfc-tools/libnfc#687]
Hello,
I am receiving an error when trying to run the "make" command in the project directory. I am receiving the following error: 
Makefile:7: *** missing separator.  Stop.

Lines 7 to 9:
if EXAMPLE_ENABLED
SUBDIRS += examples
endif

Moreover, can I use this library to write records onto Desfire EV1 cards using a uFR nano reader with this driver: 
![driverquestion](https://user-images.githubusercontent.com/55396631/218064595-8ab4d5a6-3fe6-4432-afed-0db4bfae3244.PNG)

**Comment by neomilium** [comment]
AFAICR, this device is not supported.
