### ISSUE TITLE
macOS ventura: Unable to claim USB interface (Permission denied)

### ISSUE THREAD

**Issue by luu176** [nfc-tools/libnfc#698]
Hi, I am on macOS and I keep getting this issue:

command: nfc-mfclassic r a u mycard.mfd
error	libnfc.driver.acr122_usb	Unable to claim USB interface (Permission denied)
nfc-mfclassic: ERROR: Error opening NFC reader

I have tried so many fixes, I don't know what to do anymore.

**Comment by neomilium** [comment]
`dmesg` explains it well: the device is already claimed by another process.
